title: ""
languages: 'ja'
default_lang: 'ja'
defaults:
  -
    scope:
      path: "wikiref" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default" #"default" #"project"
      category: "default"  #"default" # "project"
  -
  scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "project" #"new" #"default" 
      category: "project" #"new" #"default" 
