title: "Guro326.github.io"
languages: 'ja'
default_lang: 'ja'

defaults:
  -
  scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
   values:
      layout: "default" # "page" #
      category: "default" #"new" #"default"
#  -
#  scope:
#      path: "./wikiref.md" # an empty string here means all files in the project
#      type: "pages"
#    values:
#      layout: "page2" #"default" #"project"
#      category: "default"  #"default" # "project"
      
